### ISSUE TITLE
SayFor class

### ISSUE THREAD

**Issue by MystPi** [DavidBuchanan314/boiga#2]
Currently there's only a Say class which results in the sprite saying something indefinitely until it's reset. It would be great if there was a SayFor class that accepts a number of seconds, much like Scratch's `say [x] for (y) seconds`.

**Comment by MystPi** [comment]
Another addition I need would be the `stop [this script v]` block, as I use it quite a lot.

I hope I'm not bugging you too much with these requests, I just find this library incredibly cool and useful. 😸

**Comment by MystPi** [comment]
It would also be cool if lists had a `list.last()` method or let them accept strings as indexes, e.g. `list['last']`.

**Comment by DavidBuchanan314** [comment]
I'm happy to have feature requests! I've just been implementing the things I use in my projects as I need them, but my end-goal is to support every block, so feature requests help me prioritise what to add.

**Comment by DavidBuchanan314** [comment]
The 1-indexed `list.item()` feature I just added works with `list.item("last")` - although that's a bit of a "hacked block" which the ST might be unhappy about. I will add a special case to make it use `(("last") join (""))` in place of `"last"` (which, iiuc, is how you'd acheive list["last"] in standard scratch?)

**Comment by MystPi** [comment]
Yeah, that's correct.

Thank you for implementing that feature; it's really helpful for the porting of https://scratch.mit.edu/projects/656533955/.

**Comment by DavidBuchanan314** [comment]
Ah cool - by the way, I'm thinking about making an automatic "scratch-to-boiga" converter, so you can convert existing scratch projects and start editing them using boiga.

**Comment by MystPi** [comment]
That sounds really interesting; kind of like the Scratch-to-Snap converter.
