### ISSUE TITLE
Forever doesn't seem to work

### ISSUE THREAD

**Issue by MystPi** [DavidBuchanan314/boiga#3]
When trying to run this code,
```py
import boiga as b

project = b.Project()

cat = project.new_sprite('Scratch Cat')
cat.add_costume('scratchcat', 'boiga/examples/assets/scratchcat.svg')
i = cat.new_var('i', 1)

cat.on_flag([
    i <= 1,
    b.Repeat(10, [
        b.Say(i),
        i.changeby(1)
    ]),
    b.Forever([
        b.SetXYPos(b.MouseX(), b.MouseY())
    ])
])

project.save('test.sb3')
```
I get this error:
```
Traceback (most recent call last):
  File "c:\Users\~snip~\Projects\boiga-test\main.py", line 15, in <module>
    b.Forever([
TypeError: 'ForeverHack' object is not callable
```
Am I doing something wrong? I'm still getting used to Boiga's unique API.

**Comment by DavidBuchanan314** [comment]
Take a look at the example usage here https://github.com/DavidBuchanan314/boiga/blob/main/examples/all_supported_blocks.py#L122-L124 (you need to do it without the round brackets - although I'll consider making that an option)

This is something I'll document properly, eventually...

**Comment by MystPi** [comment]
Thanks for the help! That makes more sense.
