### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by MystPi** [DavidBuchanan314/boiga#6]
It would be nice if Boiga was uploaded to PyPI — it's somewhat unintuitive to have to clone the repo to use the library.

**Comment by DavidBuchanan314** [comment]
Yes, I'll consider this once I hit version 1.0.0 (which I think will happen once I have all the blocks implemented). One issue is that the package name `boiga` is already taken - so it'll have to be something else.

**Comment by MystPi** [comment]
Good to know. `boiga-scratch` or `pyboiga` might be good alternatives for the name of the package on PyPI.
